---
title: "Pythonの基本構文"
author: "Yusuke Nobe"
date: today
execute: 
  echo: true
  warning: false
  message: true
format: 
  html:
    fig-width: 5
    fig-height: 3
---

## イントロダクション

これからPythonの構文について学んでいく。
プログラミングの有名な構文として`if`文や`for`文などがあるが、本節ではそういった複雑な内容は扱わず、もっと基本的な計算や`print()`文、変数について学んでいく。

最初はPythonで計算をする方法について学んでいく。
Pythonを電卓代わりに使えるようになろう！

## 計算の仕方

Pythonでは足し算引き算などの四則演算に加え、累乗、剰余の計算などさまざまな演算ができる。
以下の表に各演算で用いる演算子と使用例、実行結果をまとめる。

| 演算子 | 説明 | 例 | 実行結果 |
|---|:---|:---|:---|
|`+`|足し算（加法）|`6 + 3`|9|
|`-`|引き算（減法）|`6 - 3`|3|
|`*`|かけ算（乗法）|`6 * 3`|18|
|`/`|割り算（除法）|`6 / 3`|2|
|`%`|割り算の余り（剰余）|`6 % 3`|0|
|`**`|累乗|`6 ** 3`|216|

演算子は組み合わせて使うこともできる。
例えば $5 \times 3 + 4$ という計算をしたいときは、

```{python}
5 * 3 + 4
```

と書けば良い。

なお通常の算用計算と同様に、プログラミング言語でも「かけ算・割り算は足し算・引き算より先に計算する」という優先順位が定められている。
演算子の優先順位について以下の表にまとめておく。

| 優先順位 | 演算子 | 説明 |
|:---:|---|---|
|高| `**` |累乗|
|中|`*`, `/`, `%`|かけ算、割り算、剰余|
|低|`+`, `-`|足し算、引き算|

## `print()`文のいろは

Pythonで数値や文字列などを出力するときには`print()`文を使う。
例えば「Hello, World!」と出力したいときには、

```{python}
print("Hello, World!")
```

と、文字列を`""`（ダブルクォーテーション）で囲って記述し、$3.14$という数値を出力したいときには、

```{python}
print(3.14)
```

と、`""`で囲わず記述する。

つまり文字列を出力したいときには引数を`""`で囲い、数値を出力したいときには引数を`""`で囲わず記述する。

### `print()`文で演算

`print()`文は演算もできる。
先の $5 \times 3 + 4$ を`print()`で計算したいときには

```{python}
print(5 * 3 + 4)
```

と記述し、実行する。

#### 文字列の演算

また、文字列同士の演算も行える。
「文字列同士の演算？？？」と疑問に思われるかもしれないが、例えば「おはようございます。今日の天気は晴れです。」という文字列を出力したいとしよう。

このとき、今までに学んだ知識を使えば、

```{python}
print("おはようございます。今日の天気は晴れです。")
```

と記述する。
しかし、
```{python}
print("おはようございます。" + "今日の天気は晴れです。")
```

と記述することでも、同様の文字列を出力できる。
このコードは「おはようございます。」と「今日の天気は晴れです。」を足し合わせる、つまり**演算する**ことで、「おはようございます。今日の天気は晴れです。」を出力させている。

また、掛け算を使えば次のようなこともできる。

```{python}
print("Pythonは" + "とっても" * 3 + "楽しい言語です" + "！" * 5) 
```

上記のコードではかけ算を使って、「とっても」を3回、「！」を5回出力している。
同じような言葉を何回も書くのは極めて面倒であるため、この技術はぜひとも身につけたい。

### エスケープシーケンス

`print()`文では`"`や`'`などは引用符として使われているため、単純に`print(")`や`print(')`と記述するだけでは出力できない。
ためしに1回やってみよう。

```{python}
#| error: true
print(""") 
```

やはりエラーが出た。

よってこれらを出力させるために**エスケープシーケンス**と呼ばれる特殊な記号が存在する。
使い方は簡単で、`"`や`'`の前に`\`（バックスラッシュ）を書いて実行するだけである。

```{python}
print("\"")
```

これで`"`が出力できた。

また、エスケープシーケンスは文字列の改行の際にも使われる。
使い方は改行したいところに`\n`を書くだけで、例えば

```{python}
print("おはようございます。\n今日の天気は晴れです。")
```

と書けば、きれいに改行された出力結果になる。

最後にエスケープシーケンスの表記とその意味についてまとめておく。

| 表記 | 意味 |
|---|---|
|`\n`|改行|
|`\"`|"（ダブルクォーテーション）の出力|
|`\'`|'（シングルクォーテーション）の出力|
|`\\`|\（バックスラッシュ）の出力|

## 変数

文字列の演算でPythonの便利さを実感したが、本節ではさらに便利な道具を学んでいく。
それが**変数**である。

これまでの知識であれば、「おはようございます。今日の天気は晴れです。」と出力したいとき、わざわざ`print("おはようございます。今日の天気は晴れです。")`と、毎回毎回記述しなければならなかった。
しかし変数を使えば、「おはようございます。今日の天気は晴れです。」を打ち込むのは最初の1回で済むようになる。

まずは変数の使い方について学んでいこう。
変数に「おはようございます。今日の天気は晴れです。」を代入するには、以下のようなコードを実行する。
ここでは変数名を`mor`にするが、変数名は一部を除けばどのような名前でも良い。

```{python}
mor = "おはようございます。今日の天気は晴れです。"
```

`print(mor)`を実行してみると、

```{python}
print(mor)
```

！！！<br>
あんなにタイピングしなければならなかった「おはようございます。今日の天気は晴れです。」が、たったの`mor`の3タイプだけで出力できた（`print()`は除く）。

もちろん、演算も可能である。
`mor_2`に「おはようございます。」を、`wx`に「今日の天気は晴れです。」を代入し、変数同士を足し合わせると、

```{python}
mor_2 = "おはようございます。"
wx = "今日の天気は晴れです。"
print(mor_2 + wx)
```

と、文字列の演算ができる。

### ラベル型代入について

一口に代入と言っても、それが「ハコ型」の代入を指すのか「ラベル型」の代入を指すのかはプログラミング言語によって異なる。

ハコ型代入とは変数というハコに値を格納する動作を指し、Javaの基本データ型の代入などがこれにあたる（`String()`クラス等のクラスではラベル型になる）。
例えばJavaで

```java
public static void main(String[] args) {
  int x = 5;
}
```

と記述すれば、変数`x`というint型のハコに5が格納されることになる（ここではJavaのコードの書き方について理解する必要はない）。

一方Pythonでも同様に、

```{python}
x = 5
```

と変数`x`に5を代入しても、これは変数`x`というハコに5を格納したとは解釈しない。
Pythonにおける代入の解釈の仕方は「5という整数に`x`というラベルを張り付けた」であり、これこそがラベル型の代入の考え方である。

### 変数のメモリについて

Pythonの代入はラベル型の代入であるため、複数の変数に同じ値を代入したとき、各変数は同じメモリアドレスに存在することになる。
メモリアドレスとは、その変数が存在する住所という理解でいいだろう。

では実際に複数の変数に同じ値を代入し、各変数のメモリアドレスを表示してみよう。まずは各変数に同じ値を代入してみる。

```{python}
x = 5
y = 5
z = 5
```

変数`x`のメモリアドレスは、

```{python}
id(x)
```

変数`y`のメモリアドレスは、

```{python}
id(y)
```

変数`z`のメモリアドレスは、
```{python}
id(z)
```

である。

一見同じメモリアドレスのように見えるが、人間の目など当てにならないため、プログラムを組んで確認しよう。
次のプログラムは3つの変数がいずれも同じメモリアドレスに属す場合のみ`True`を、そうでなければ`False`を出力するように組まれている（内容については今は理解しなくて良い）。

```{python}
if (id(x) == id(y) and id(x) == id(z)):
  print(True)
else:
  print(False)
```

`True`が出力された。
つまり3変数のメモリアドレスがいずれも同じだということである。

小難しい話は以上にして、次節からは変数の使い方をさらに学んでいこう。

### 変数の利用

変数は冒頭で説明したように文字列を代入したり、数値を代入したりする。
ここで改めて文字列や数値の代入の仕方について復習しておこう。

まず文字列は`""`で囲って代入する。
```{python}
string = "ほげほげ"
```

数値の場合は`""`で囲わず代入する。

```{python}
num = 3
```

小数の場合も同様。

```{python}
number = 3.14
```

さて、変数の基本についてある程度分かってきた。
次は変数に計算結果を代入していく。

#### 変数を用いて円の面積の計算

例えば「半径5の円の面積を求めよ」という問題があったとする。
円の面積の公式が、面積を $S$ 、半径を $r$、円周率を $\pi$ としたとき

$$
S = \pi r^2
$$

であることは広く知られているが、ここでは半径を $5$ 、円周率を $3.14$ として面積をPythonに計算させて変数 $S$ に代入してみよう。

このとき、以下のようなコードを書く。

```{python}
S = 5 * 5 * 3.14
print(S)
```

また、半径や円周率を変数に代入したのち、面積を計算しても良い。

```{python}
r = 5
pi = 3.14
S = pi * r**2
print(S)
```

今まで学んできた内容を駆使すれば、上記のコードは簡単に理解できるだろう。

#### 計算結果を自分自身に代入
\label{result}

この資料を作成している現在の西暦は2026年である。
よって`year`という変数に2026を代入してみる。

```{python}
year = 2026
```

しかし来年になれば2027年になり、さらに1年たてば2028年になってしまう。

「今年は2026年で、来年には2027年になり、さらに1年たてば2028年になる。」という文章を変数を使って出力するにはどうすればよいだろうか。

案の一つとして変数を増やすことが挙げられる。
つまり`year`に2026を代入したのであれば、`year_2`に2027を、`year_3`に2028を代入すればよいという案である。
実際に実行してみよう。

```{python}
year = 2026
year_2 = 2027
year_3 = 2028
print("今年は")
print(year)
print("年で、来年には")
print(year_2)
print("年になり、さらに1年たてば")
print(year_3)
print("年になる。")
```

たしかに欲しい文章は出力できたが、これでは毎年毎年新しい変数を作っていかなければならない。
仮にこれが`date`という変数で毎日変更されていくとなれば、大量の変数が必要になってしまう。

こんなときには、計算結果を自分自身に代入するという方法をとる。
今回でいえば、`year + 1`の結果を`year`に代入することになる。
試しにもう一度`year`に2026を代入してから、この方法を実行してみよう。

```{python}
year = 2026
print("今年は")
print(year)
year = year + 1 # 計算結果を自分自身に代入
print("年で、来年には")
print(year)
year = year + 1 # 計算結果を自分自身に代入
print("年になり、さらに1年たてば、")
print(year)
print("年になる。")
```

今回は`year`という変数だけで、欲しい文章を出力できた。
この方法は`for`文でよく使われるため、ぜひとも身につけたい。

なお、`year = year + 1`というコードは、

```{python}
year += 1
```

と、変数を1度しか書かない簡単なコードで記述することもできる。

これをつかって先の文章を出力してみよう。

```{python}
year = 2026
print("今年は")
print(year)
year += 1 # 簡単なコードで計算結果を自分自身に代入
print("年で、来年には")
print(year)
year += 1 # 簡単なコードで計算結果を自分自身に代入
print("年になり、さらに1年たてば、")
print(year)
print("年になる。")
```

タイプ数が減るため非常に役立つ。
うれしい。

### 単純な`print()`文の限界

4.3.2節の最後のコードでは

```{python}
year = 2026
print("今年は")
print(year)
year += 1 # 簡単なコードで計算結果を自分自身に代入
print("年で、来年には")
print(year)
year += 1 # 簡単なコードで計算結果を自分自身に代入
print("年になり、さらに1年たてば、")
print(year)
print("年になる。")
```

と、7つもの`print()`文を書き、7行の出力結果を得た。
このくらいの出力量なら出力結果は1行でいいし、毎回毎回`print()`文を書くのも面倒くさい。

ここでは`print()`文を1回だけで済ます方法について学んでいこう。

とはいえ、どうすれば`print()`文を1回書くだけで済ませられるだろうか。
Javaであれば以下のようなコードを打つ。

```java
public static void main(String[] args) {
  int year = 2026;
  System.out.println("今年は" + year + "年で、来年には" + (year + 1) + "年になり、さらに1年たてば" + (year + 2) + "年になる。");
}
```

これを参考にPythonでも`print()`文を書いてみよう。

```{python}
#| error: true
year = 2026
print("今年は" + year + "年で、来年には" + (year + 1) + "年になり、さらに1年たてば、" + (year + 2) + "年になる。")
```

エラーが出力されてしまった。
エラー文をGoogle翻訳にかけてみると「文字列に連結できるのは文字列のみで、整数は連結できません。」と翻訳された。

ここから分かる通り、Pythonの単純な`print()`文には文字列と整数を連結できないという限界がある。

### 型の変換

先ほど吐き出されたエラー文中に、`str`や`int`という言葉がある。
これらのことを**型**（または**データ型**）といい、`str`は「文字列」を、`int`は「整数」を意味する。

その他、型についてまとめると、以下の表のようになる。

| 型の名前 | 説明 |
|---|---|
|int|整数|
|float|浮動小数点数（小数のこと）|
|str|文字列（文字も含む）|
|bool|真偽値|

Pythonには`type()`関数という、引数の型を教えてくれる関数がある。
試しに色々な変数の型を調べてみよう。

```{python}
x = 123
type(x)
```
```{python}
y = 1.4142
type(y)
```
```{python}
String = "ほげほげ"
type(String)
```

なお、変数以外を引数にしても型を教えてくれる。

```{python}
type("おはよう世界")
```

なるほどなるほど。
型についてある程度分かってきた。

またすばらしいことに、Pythonには型の変換を**簡単**に行うことができる関数がある。
そのすばらしい関数とは以下のとおりである。

| 関数名 | 説明 |
|---|---|
|`int()`関数|引数を`int`型に変換したものを戻り値として返す|
|`float()`関数|引数を`float`型に変換したものを戻り値として返す|
|`str()`関数|引数を`str`型に変換したものを戻り値として返す|
|`bool()`関数|引数を`bool`型に変換したものを戻り値として返す|

試しに`123`という、`int`型の値を代入した変数`x`を`str`型に変換してみよう。
```{python}
x = 123
x = str(x)
type(x)
```

`type(x)`によって`str`が出力されていることから、`str(x)`によって変数`x`が`str`型に変換されたことが確認できる。

これを使って冒頭のコードを`print()`文1つで実行してみよう。

```{python}
year = 2026
print("今年は" + str(year) + "年で、来年には" + str(year + 1) + "年になり、さらに1年たてば、" + str(year + 2) + "年になる。")
```

これにて本節の悲願達成である。

### 便利な`print()`文のご紹介

4.4節にて、`print()`文では異なる型を連結できないという限界があることを学んだ。
それを受けて4.5節では型の変換という手法を学んだわけだが、4.5節の最後のコードも`+`が多くて少し見づらい。

よって本節では`print()`文で`+`を使わず異なる型を連結する方法について軽く紹介する。

まず一つ目が`format()`関数を使う方法である。
これを使えば、異なる型を連結した`print()`文を記述することができる。

```{python}
year = 2026
print("今年は{}年で、来年には{}年になり、さらに1年たてば{}年になる。"
    .format(year, year + 1, year + 2))
```

また、もう一つの方法として、**f-string**がある。
これは以下のように`print()`文の引数の先頭に`f`をつけて用いる。

```{python}
year = 2026
print(f"今年は{year}年で、来年には{year + 1}年になり、さらに1年たてば{year + 2}年になる。")
```

`format()`関数を使う場合と比べて、単純な`print()`文に`f`を付け加えるだけで済むため、非常に簡単かつ楽である。