---
title: "プログラミング言語の分類"
author: "Yusuke Nobe"
date: today
execute: 
  echo: true
  warning: false
  message: true
format: 
  html:
    fig-width: 5
    fig-height: 3
---

## コンパイル型？インタプリタ型？

Pythonはインタプリタ型の言語として知られており、もう一つの型としてコンパイル型がある。
しかしインタプリタもコンパイルもまったく意味が分からないし、聞いたことすらない。

簡単に言えばプログラミング言語を分類する方法の一つであるが、それだけでは双方の違いやメリット / デメリットが不明だ。
よって本節ではコンパイル型とインタプリタ型の違いとそのメリット / デメリットについて学んでいこう。

### コンパイル型とインタプリタ型の違い

コンパイル型とインタプリタ型の違いはプログラム実行の仕方にある。

コンパイル型言語ではソースコードを最後まで書き上げてから実行し、この実行を**コンパイル**という。
コンパイルはコンパイラによって行われ、以下の5過程を経てオブジェクトコードと呼ばれる0と1を羅列したコードを生成する。

1. 字句解析
2. 構文解析
3. 意味解析
4. 最適化
5. コード生成

5つの過程のうち最も重要なのは4の最適化だ。
コンパイラがソースコードの改善を行ってくれることを最適化と言い、これによってよりファイルサイズなどの面でより効率的なプログラムが作成できる。

一方でインタプリタ型の言語ではソースコードを1文ずつ解釈しながら実行する<sup><a href = "#foot1">1)</a></sup>。
つまりコンパイルを経ることなくプログラムを実行できるため、少しソースコードを書いたらすぐに実行できる。
よってインタプリタ型の言語は時間的に効率よく、ソフトウェアを開発できるとされている。

### メリット / デメリット

ここまでの説明でおおよそ見当がつくが、改めてコンパイル型・インタプリタ型のメリット / デメリットについて学んでおく。

#### コンパイル型のメリット / デメリット

コンパイル型のメリットは最適化を行うことで、より効率的なプログラムを作成できることにあるだろう。
プログラムのファイルサイズを小さくできるということは誰にとってもハッピーである。

一方デメリットとして、コンパイルやエラーの特定に時間を要することが挙げられる。<br>
<a href = https://kut-econ.github.io/programming2025/programming-1.html#%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E8%A8%80%E8%AA%9E%E3%81%AE%E7%A8%AE%E9%A1%9E>高知工科大学小林先生の資料</a>に、「C言語（コンパイル型の言語のひとつ）で作られた膨大なプログラムはコンパイルだけで数時間を要する」とある。
ソフトウェア開発においてコンパイルとは作業の一つにすぎないため、これで数時間を食らうのは時間的に非常に惜しい。<br>
また、先にも記した通り、コンパイル型の言語はソースコードを最後まで書きあげてから実行する。
よってある程度の量のコードを書いてから始めて実行することになるため、エラーが起きてもどこでエラーが起きているのかがなかなか分からない。
これは英語が分からない人間にとって非常に非常に難儀である。<sup><a href = "#foot2">2)</a></sup>

#### インタプリタ型のメリット / デメリット

インタプリタ型のメリットとして実行に時間を要さないこと、エラーを瞬時に特定できることが挙げられる。
インタプリタ型の言語ではコンパイルという作業を行わないため、「コンパイルに数時間を要する」などという問題は起こらない。
また、1文ずつ実行できるということはエラーが生じてもその1文だけ見ればよいため、エラーの特定も瞬時に行える。

一方デメリットは（ファイルサイズ的に）効率的なプログラムを作成できないことである。
しかしこのデメリットはプログラム作成者が最適な素晴らしいコードを書ければ問題ない。
ただし、初心者がそんなコードを書けるわけがないため、**我々にとって**はデメリットに違いない。

### まとめ

本節ではコンパイル型言語とインタプリタ型言語の違いやメリット / デメリットについて学んできた。
サマリーすれば、コンパイル型言語は「最適化によって（ファイルサイズ的に）効率的なプログラムが作れるが、実行に時間を要する」、インタプリタ型言語は「実行に時間はかからないが、最適なコードを作れない」となるだろう。

つまりコンパイル型言語もインタプリタ型言語も一長一短であるため、どちらが良い・悪いという話ではない。
ただし個人的にはエラー特定が簡単なインタプリタ型言語のほうが、精神的に良さそうである。

<ol>
    <li id = "foot1">厳密にはバイトコード（？）と呼ばれるものを1文ずつ実行するらしいが、このあたりはあまり意味が分からないし、プログラミング言語を**道具**として使う人にとっては分からなくて知識だと良いと思う（プログラミング言語を**研究**する人は頑張って勉強してね！！！）。</li>
    <li id = "foot2">エラー文を完全に理解できる英語力さえあれば問題ないけど......</li>
</ol>