---
title: "リスト"
author: "Yusuke Nobe"
date: today
execute: 
  echo: true
  warning: false
  message: true
format: 
  html:
    fig-width: 5
    fig-height: 3
---

## イントロダクション

<a href = "basic_syntax.html">Pythonの基本構文</a>の第4節で変数について学んだ。
変数とは文字列や整数・小数などを代入できる、非常に便利な道具だと学んだが、実はこれだけでは不便なこともある。

例えば主要5科目（国・数・社・理・英）の点数を変数に代入し、合計点 (`total_score`) ・平均点 (`avarage_score`) を計算したいとしよう。
このとき、今までの知識では以下のようなコードを実行することになる。
```{python}
jap = 60
mat = 77
sor = 76
sci = 98
eng = 25
total_score = jap + mat + sor + sci + eng
avarage_score = total_score / 5
print(f"合計点: {total_score} \n平均点: {avarage_score}")
```

主要5科目の点数のためにわざわざ5つもの変数を用意するのは非常に面倒くさい。
また、学年全員の合計点や平均点を計算したいときには100や200の変数を用意しなければならなくなる。

そんな重労働を回避するためにプログラミング言語には**配列**というものがある。
Pythonでは**リスト**が他のプログラミング言語における配列に該当するだろう。
また、Pythonにはそのほかにも**辞書**や**タプル**、**セット**などが用意されている。

本節では**リスト**について学ぶ（仮に今後、必要だと感じることがあれば辞書やタプルなども追加する）。

## リスト

リストでは`[]`の中に格納したい要素を`,`区切りで記述していく。
と、言われても意味が分からないため、実際に先の5科目の点数をリストの中に入れてみよう。
リストを代入する変数名は`score`にする。
```{python}
score = [60, 77, 76, 98, 25]
print(score)
```

なお、リストの中には数値のほか、文字列（文字も含む）も格納できる。
```{python}
subject = ["国語", "数学", "社会", "理科", "英語"]
print(subject)
```

さらに、整数・小数・文字列など型が違っていても同じリストに格納できる。
```{python}
mylist = ["Hello", 5, 'あ', 1.41421356]
print(mylist)
```

### リストの要素を参照

リストに格納されている要素を参照したいときには以下のようなコードを用いる。
```{python}
my_score = [80, 90, 20, 60, 40]
math = my_score[1]
```

ここで注意すべきことは、`my_socre[1]`によって`math`に代入された数値が80ではなく90であるという点である。
実際に`math`に代入されている数値を確認してみよう。
```{python}
print(math)
```

`my_score`の80を参照したい場合には次のようにする。
```{python}
japanese = my_score[0]
```

このように、インデックスが**0から始まる**という点はリストを扱う上で最も注意しなければならない。

### リストの合計と平均の計算

ここまででリストへの格納方法、参照方法が分かった。
では第1節のように主要5科目の合計点・平均点を計算したいとき、どのようにすべきだろうか。
思いつくコードは次のようなものである。
```{python}
score = [60, 77, 76, 98, 25]
total_score = score[0] + score[1] + score[2] + score[3] + score[4]
avarage_score = total_score / 5
print(f"合計点: {total_score} \n平均点: {avarage_score}")
```

`jap`から`eng`までの変数を作成しなくて良くなったため、少し楽になった。

しかし2行目の`total_score`の計算はまだまだ面倒である。
第1節でも指摘した学年全員の合計点・平均点を計算する場合には、合計点の計算だけで膨大な量のタイピングをしなければならなくなってしまう。

これを回避するためにPythonには`sum()`関数というものが用意されている。
これはリスト内のすべての要素の合計を計算する関数で、以下のように用いる。
```{python}
score = [60, 77, 76, 98, 25]
total_score = sum(score)
print(total_score)
```

`sum()`関数を用いると、第1節のコードは次のようになる。
```{python}
score = [60, 77, 76, 98, 25]
total_score = sum(score)
avarage_score = total_score / 5
print(f"合計点: {total_score} \n平均点: {avarage_score}")
```

記述量が少ない、極めて楽なコードになった。
ただ最後にもう一つ、`len()`関数というものについて学んでおく。

`len()`関数とはリスト内の要素の個数を数えてくれる便利な関数である。
これを使うことで、リストの要素の個数が増減したとき、コードの修正量を減らせられる。
また、リストの要素の個数を数え間違えるという凡ミスを完全に無にできるというメリットもある。

使い方は次の通り。
```{python}
my_score = [80, 90, 20, 60, 40]
count_myscore = len(my_score)
print(count_myscore)
```

主要5科目の合計点・平均点を計算したいときには、以下のような使い方をする。
```{python}
score = [60, 77, 76, 98, 25]
total_score = sum(score)
avarage_score = total_score / len(score)
print(f"合計点: {total_score} \n平均点: {avarage_score}")
```

これによって仮に`score`に新しい数値が追加されても、`avarage_score`の分母は修正せずに済む。
つまり、コードの修正量が減らせられる。

### リストの修正

2.2節の最後の話で出てきたように、プログラムを組んでいるとリストに新しい数値を追加したいときがある。

例えば主要5科目に家庭科の点数`65`を追加したいとしよう。
このとき
```{python}
score = [60, 77, 76, 98, 25]
score = [60, 77, 76, 98, 25, 65]
```
と、変数`score`を上書きするという修正方法が思いつく。

これでも良いのだが、`append()`関数や`remove()`関数というリストを修正する便利な関数が存在するため、本節ではこれについて学んでいこう。

#### リスト要素の追加

冒頭の話のように、リストに要素を追加したいときには`append()`関数というものを使う。
これは引数に与えた数値や文字列をリストに追加するという機能を持ち、次のような使い方をする。
```{python}
score = [60, 77, 76, 98, 25]
score.append(65)
print(score)
```

#### リスト要素の削除

反対に、リストの要素を削除したいときには`remove()`関数というものを使う。
これは引数に与えた数値や文字列をリストから削除するという機能を持ち、次のような使い方をする。
```{python}
score = [60, 77, 76, 98, 25, 65]
score.remove(65)
print(score)
```

### 空のリストの作り方

これまではリストを作成し、そのリストに要素を格納する方法について学んできた。
しかしプログラムを組んでいると、空のリストを作りたいという感情になることがある。

よって最後に空のリストの作り方について学んでおく。

空のリストは`list()`と記述するだけで作成できる。
つまり、
```{python}
empty = list()
```

というコードを実行することで、変数`empty`には空のリストが代入されることになる。