---
title: "条件分岐"
author: "Yusuke Nobe"
date: today
execute: 
  echo: true
  warning: false
  message: true
format: 
  html:
    fig-width: 5
    fig-height: 3
---

## イントロダクション

試験の合格条件には絶対的な点数として定まっているものと周りの点数と比較して定まるものとがある。

ここで仮に「100点満点中60点以上だと合格」という試験に受験するとする。
このとき、
```
もし、試験の点数が60点以上なら・・・
    → 試験結果: 合格
そうでなければ・・・
    → 試験結果: 不合格
```
が成り立つ。

プログラムの世界でも同様に、条件によって異なる結果を実行させることが往々にしてある。
本節ではそんな**条件分岐**について学んでいこう。

## `if`文

プログラミングの世界において、最も基本的かつ最も重要な条件分岐文は`if`文である。
ifの意味は皆さまご存じ「もし」であり、`if`文では`if`のうしろに条件を書く。

例えば「試験の点数 (`score`) が60点以上」という条件を書きたいときには、
``` python
if (score >= 60): # ()は無くても良い
```
と書く。

つづいて`if (条件):`の下に条件を満たす場合に実行したいことを書く。
「試験結果: 合格」という文字列を出力したければ、
```python
if (score >= 60):
    print("試験結果: 合格")
```
と書けばよい。

条件を満たさない場合に実行したいことがあれば、さらに下に`else:`を書き、その下に実行したいことを書く。
「試験結果: 不合格」という文字列を出力したければ、
```python
if (score >= 60):
    print("試験結果: 合格")
else: 
    print("試験結果: 不合格")
```
と書けばよい。

### インデントの重要性

「条件を満たす場合に実行したいことは`if (条件)`の下に書く」と説明したが、
```python
if (score >= 60):
print("試験結果: 合格")
```
だと条件分岐はできない。
正解のコードは、
```python
if (score >= 60):
    print("試験結果: 合格")
```
であり、両コードの違いは`print("試験結果: 合格")`の前の字下げ（インデント）にある。

Pythonではインデントが**ブロック**の意味を果たすことになる。
例えば、
```python
if (score >= 60):
    print("試験結果: 合格")
```
だと2行目の`print("試験結果: 合格")`の前のインデントが「ifブロック」の意味を果たすことになり、
```python
if (score >= 60):
    print("試験結果: 合格")
else:
    print("試験結果: 不合格")
```
だと2行目の`print("試験結果: 合格")`の前のインデントが「ifブロック」、4行目の`print("試験結果: 不合格")`の前のインデントが「elseブロック」の意味を果たすことになる。

難しいことはともかくとして、「Pythonで複数行のコードを書くときはインデントに気をつける」と覚えておこう。

### 関係演算子

第2節冒頭で「試験の結果 (`score`) が60点以上」という条件を書くとき、`score >= 60`と書いた。
このコードに含まれる`>=`は**関係演算子**というものの一種であり、「左辺は右辺より大きいか等しい」という意味を持つ。

その他、関係演算子には以下のようなものがある。
いずれの関係演算子もよく使われるため、すべて覚えておきたい。

| 関係演算子 | 意味 |
|---|---|
|`==`|左辺と右辺は等しい|
|`!=`|左辺と右辺は等しくない|
|`>`|左辺は右辺より大きい|
|`>=`|左辺は右辺より大きいか等しい（左辺は右辺以上）|
|`<`|左辺は右辺より小さい|
|`<=`|左辺は右辺より小さいか等しい（左辺は右辺以下）|

### 論理演算子

資格の中には科目が複数種類あり、そのすべてである程度の点数を取らなければならないというものもある。

たとえば資格Xに科目Aと科目Bがあり、「科目Aと科目Bの両方で1000点満点中600点以上」という合格条件があったとする。
このとき、
```
もし、科目Aが600点以上かつ科目Bも600点以上なら・・・
    → 試験結果: 合格
そうでなければ・・・
    → 試験結果: 不合格
```
が成り立つ。

これをプログラムで成立させるとき、`and`という**論理演算子**を用いることになる。
`and`は「かつ」を意味し、以下のように用いる。
```python
if (A >= 600 and B >= 600):
    print("試験結果: 合格")
else:
    print("試験結果: 不合格") 
```

その他、論理演算子には以下のようなものがある。
関係演算子と同様、いずれもよく使われるためすべて覚えておきたい。

| 論理演算子 | 意味 |
|---|---|
|`and`|かつ|
|`or`|または|
|`not`|でなければ|

`not`の使い方だけ追加で学んでおこう。
第1節の資格の話を逆転して考えてみると、

```
もし、資格の点数が60点未満でなければ・・・
    → 試験結果: 合格
そうでなければ・・・
    → 試験結果: 不合格
```

が成り立つ。これは`not`を用いれば、
```python
if (not (score < 60)):
    print("試験結果: 合格")
else:
    print("試験結果: 不合格")
```

と表すことができる。

## `if-elif`文

大学の授業では「合格（単位取得）・不合格（落単）」以外に「AA」や「A」などの評価が与えられる。

仮にこれらの評価がテストの点数に基づいて与えられる場合、
```
もし、テストの点数が90点以上なら・・・
    評価: AA
そうでなく、もしテストの点数が80点以上なら・・・
    評価: A
そうでなく、もしテストの点数が70点以上なら・・・
    評価: B
そうでなく、もしテストの点数が60点以上なら・・・
    評価: C
そうでなければ・・・
    評価: F
```
と表すことができる。

このような条件分岐をPythonで実行する場合、`if-elif`文という構文を使用する。

`if-elif`文の書き方は以下の通りである。
```python
if (score >= 90):   # もしテストの点数が90点以上なら・・・
    print("評価: AA")
elif (score >= 80): # そうでなく、もしテストの点数が80点以上なら・・・
    print("評価: A")
elif (score >= 70): # そうでなく、もしテストの点数が70点以上なら・・・
    print("評価: B")
elif (score >= 60): # そうでなく、もしテストの点数が60点以上なら・・・
    print("評価: C")
else:
    print("評価: F")
```

なお、`elif`とは`else if`の略称である。
よって「そうでなく、もし〇〇なら」と解釈する。

